import * as yup from "yup";

export const userSchema = yup.object().shape({
  firstName: yup.string().required(),
  lastName: yup.string().required(),
  email: yup.string().required(),
  gender: yup.string().required(),
  userId: yup.string().required(),
  mobileNumber: yup.string().required(),
  alternateContact: yup.string().required(),
  role: yup.string().required(),
  category: yup.string().required(),
  samagraId: yup.string().required(),
  bloodGroup: yup.string().required(),
  religion: yup.string().required(),
  nationality: yup.string().required(),
  classId: yup.string().required(),
  studentId: yup.string().required(),
  contact: yup.string().required(),
  uid: yup.string().required(),
  bankAccountNo: yup.string().required(),
  familyAnnualIncome: yup.string().required(),
  enrollmentNo: yup.string().required(),
  disabilityType: yup.string().required(),
  fees: yup.number().required(),
  disabilityPercentage: yup.string().required(),
  password: yup.string().required(),
  state: yup.string().required(),
  birthDate: yup.string().required(),
  zip: yup.number().required(),
  discount: yup.number().required(),
  ParentContact1: yup.number().required(),
  ParentContact2: yup.number().required(),
  fatherName: yup.string().required(),
  occupationFather: yup.string().required(),
  motherName: yup.string().required(),
  occupationMother: yup.string().required(),
  familyId: yup.string().required(),
  bankName: yup.string().required(),
  backAccountNo: yup.string().required(),
  ifscCode: yup.string().required(),

  flatDoorBlock: yup.string().required(),
  village: yup.string().required(),
  postOffice: yup.string().required(),
  locality: yup.string().required(),
  city: yup.string().required(),

  qualification: yup.string().required(),
  passingYear: yup.string().required(),
  board: yup.string().required(),
  marks: yup.number().required(),
  resultPercentage: yup.string().required(),
  schoolName: yup.string().required(),

  terms: yup.bool().required().oneOf([true], "Terms must be accepted"),
});
